InAndOut/Models/ErrorViewModel.cs
using System;

namespace InAndOut.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

InAndOut/Models/Expense.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel;

namespace InAndOut.Models
{
    public class Expense
    {
        [Key]
        public int Id { get; set; }
        [DisplayName("Expense Name")]
        [Required]
        public string ExpenseName { get; set; }
        [Required]
        [Range(1,int.MaxValue,ErrorMessage ="Amount must be greater than 0!")]
        public int Amount { get; set; }
    }
}

InAndOut/Models/Item.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel;

namespace InAndOut.Models
{
    public class Item
    {
        [Key]
        public int Id { get; set; }
        public string Borrower { get; set; }
        public string Lender { get; set; }
        [DisplayName("Item name")]
        public string ItemName { get; set; }
    }
}

InAndOut/Controllers/AppointmentController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace InAndOut.Controllers
{
    public class AppointmentController : Controller
    {
        public IActionResult Index()
        {
            String todays = DateTime.Now.ToShortDateString();
            // return View();       
            return Ok(todays);
            
        }
        public ViewResult Rajesh()
        {

            return View();
        }
    }
}

InAndOut/Controllers/ExpenseController.cs
using InAndOut.Data;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using InAndOut.Models;

namespace InAndOut.Controllers
{
    public class ExpenseController : Controller
    {
        ApplicationDbcontext db_;

        public ExpenseController(ApplicationDbcontext dbcontext)
        {
            db_ = dbcontext;
        }
        public IActionResult Index()
        {
            var expenses = db_.Expenses;
            return View(expenses);
        }
        //Get Create
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Expense expense)
        {
            if (ModelState.IsValid)
            {
                db_.Expenses.Add(expense);
                db_.SaveChanges();
                return RedirectToAction("index");
            }
            return View(expense);
        }

     //get upadte
        public IActionResult Update(int? id)
        {
           var expensedata= db_.Expenses.FirstOrDefault(x => x.Id ==id);
           
          
            return View(expensedata);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Update(Expense expense)
        {
            if (ModelState.IsValid)
            {
                db_.Expenses.Update(expense);
                db_.SaveChanges();
                return RedirectToAction("index");
            }
            return View(expense);
        }

        public IActionResult Delete(int? id)
        {
            var expensedata = db_.Expenses.FirstOrDefault(x => x.Id == id);


            return View(expensedata);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult DeletePost(int? id)
        {
             var expenseobject=db_.Expenses.FirstOrDefault(x=>x.Id==id);

            db_.Expenses.Remove(expenseobject);
            db_.SaveChanges();
            return RedirectToAction("index");
        }
    }
}

InAndOut/Controllers/HomeController.cs
using InAndOut.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace InAndOut.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

InAndOut/Controllers/ItemController.cs
using InAndOut.Data;
using InAndOut.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace InAndOut.Controllers
{
    public class ItemController : Controller
    {
        ApplicationDbcontext db_;

        public ItemController(ApplicationDbcontext dbcontext)
        {
            db_ = dbcontext;
        }
        public IActionResult Index()
        {
           var items= db_.Items;
            return View(items);
        }
        //Get Create
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Item item)
        {
            db_.Items.Add(item);
            db_.SaveChanges();
            return RedirectToAction("index");
        }
    }
}

InAndOut/Views/Appointment/Rajesh.cshtml
@{
    ViewData["Title"] = "Rajesh";
}

<h1>Rajesh</h1>

InAndOut/Views/Expense/Create.cshtml
@model InAndOut.Models.Expense;
<form method="post" asp-action="Create">
    <div class="border p-3">
        @*<div asp-validation-summary="All" class="text-danger"></div>*@
        <div class="form-group row">
            <h2 class="text-black-50 pl-3">Add Expense item</h2>
        </div>
        <div class="row">
            <div class="col-12">
                <div class="form-group row">
                    <div class="col-6">
                        <label asp-for="ExpenseName"></label>
                    </div>
                    <div class="col-6">
                        <label asp-for="Amount"></label>
                    </div>
                   
                </div>
                <div class="form-group row">
                    <div class="col-6">
                        <input asp-for="ExpenseName" class="form-control" />
                        <span asp-validation-for="ExpenseName" class="text-danger"></span>
                    </div>
                    <div class="col-6">
                        <input asp-for="Amount" class="form-control" />
                        <span asp-validation-for="Amount" class="text-danger"></span>
                    </div>
                   
                </div>
                <div class="form-group row">
                    <div class="col-8 offset-2 row">
                        <div class="col">
                            <input type="submit" class="btn btn-info w-75" value="Create" />
                        </div>
                        <div class="col">
                            <a class="btn btn-danger w-75" asp-action="Index">Back</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>

@section Scripts{
    @{ <partial name="_ValidationScriptsPartial"/>}

}

InAndOut/Views/Expense/Delete.cshtml
<form method="post" asp-action="DeletePost">
</form>
@model InAndOut.Models.Expense;
<form method="post" asp-action="DeletePost">
    <input asp-for="Id" hidden/>
    <div class="border p-3">
        @*<div asp-validation-summary="All" class="text-danger"></div>*@
        <div class="form-group row">
            <h2 class="text-black-50 pl-3">Add Expense item</h2>
        </div>
        <div class="row">
            <div class="col-12">
                <div class="form-group row">
                    <div class="col-6">
                        <label asp-for="ExpenseName"></label>
                    </div>
                    <div class="col-6">
                        <label asp-for="Amount"></label>
                    </div>

                </div>
                <div class="form-group row">
                    <div class="col-6">
                        <input asp-for="ExpenseName" class="form-control" disabled />
                       
                    </div>
                    <div class="col-6">
                        <input asp-for="Amount" class="form-control" disabled />
                        
                    </div>

                </div>
                <div class="form-group row">
                    <div class="col-8 offset-2 row">
                        <div class="col">
                            <input type="submit" class="btn btn-info w-75" value="Delete" />
                        </div>
                        <div class="col">
                            <a class="btn btn-danger w-75" asp-action="Index">Back</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>

@section Scripts{
    @{
        <partial name="_ValidationScriptsPartial" />

    }

}

InAndOut/Views/Expense/Index.cshtml
@model IEnumerable<InAndOut.Models.Expense>

<div class="container p-3">
    <div class="row pt-4">
        <div class="col-6">
            <h2 class="text-primary">Expenses</h2>
        </div>
        <div class="col-6 text-right">
            <a asp-controller="Expense" asp-action="Create" class="btn btn-primary">create new Expense List</a>
        </div>
    </div>
    <br />
    @if (Model.Count() > 0)
    {
        <table class="table table-bordered table-striped" style="width:100%">
            <thead>
                <tr>
                    <th>Expense Name</th>
                    <th>Amount</th>
                  
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td width="35%">@item.ExpenseName</td>
                        <td width="35%">@item.Amount</td>  
                        <td width="30%">
                            <div class="w-100 btn-group" role="group">
                                <a asp-controller="Expense" asp-action="Update"  asp-route-Id="@item.Id" class="btn btn-primary mx-1">Update</a>
                                <a asp-controller="Expense" asp-action="Delete"  asp-route-Id="@item.Id" class="btn btn-danger mx-1">Delete</a>
                            </div>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    }
</div>

InAndOut/Views/Expense/Update.cshtml
<form method="post" asp-action="Update">
</form>
@model InAndOut.Models.Expense;
<form method="post" asp-action="Update">
    <div class="border p-3">
        @*<div asp-validation-summary="All" class="text-danger"></div>*@
        <div class="form-group row">
            <h2 class="text-black-50 pl-3">Add Expense item</h2>
        </div>
        <div class="row">
            <div class="col-12">
                <div class="form-group row">
                    <div class="col-6">
                        <label asp-for="ExpenseName"></label>
                    </div>
                    <div class="col-6">
                        <label asp-for="Amount"></label>
                    </div>

                </div>
                <div class="form-group row">
                    <div class="col-6">
                        <input asp-for="ExpenseName" class="form-control" />
                        <span asp-validation-for="ExpenseName" class="text-danger"></span>
                    </div>
                    <div class="col-6">
                        <input asp-for="Amount" class="form-control" />
                        <span asp-validation-for="Amount" class="text-danger"></span>
                    </div>

                </div>
                <div class="form-group row">
                    <div class="col-8 offset-2 row">
                        <div class="col">
                            <input type="submit" class="btn btn-info w-75" value="Update" />
                        </div>
                        <div class="col">
                            <a class="btn btn-danger w-75" asp-action="Index">Back</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>

@section Scripts{
    @{
        <partial name="_ValidationScriptsPartial" />

}

    }

InAndOut/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

InAndOut/Views/Item/Create.cshtml
@model InAndOut.Models.Item;
<form method="post" asp-action="Create">
    <div class="border p-3" >
        <div class="form-group row">
            <h2 class="text-black-50 pl-3">Add item</h2>
        </div>
        <div class="row">
            <div class="col-12">
                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="ItemName"></label>
                    </div>
                    <div class="col-4">
                        <label asp-for="Borrower"></label>
                    </div>
                    <div class="col-4">
                        <label asp-for="Lender"></label>
                    </div>
                </div> 
                <div class="form-group row">
                    <div class="col-4">
                       <input asp-for="ItemName"class="form-control"/>
                    </div>
                    <div class="col-4">
                        <input asp-for="Borrower" class="form-control"/>
                    </div>
                    <div class="col-4">
                        <input asp-for="Lender" class="form-control"/>
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-8 offset-2 row">
                        <div class="col">
                            <input type="submit" class="btn btn-info w-75" value="Create" />
                        </div>
                        <div class="col">
                            <a class="btn btn-danger w-75" asp-action="Index">Back</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>

InAndOut/Views/Item/Index.cshtml
@model IEnumerable<InAndOut.Models.Item>

<div class="container p-3">
    <div class="row pt-4">
        <div class="col-6">
            <h2 class="text-primary">Borrowed Items List</h2>
        </div>
        <div class="col-6 text-right">
           <a asp-controller="Item" asp-action="Create" class="btn btn-primary">create new item</a>
        </div>
    </div>
    <br />
    @if (Model.Count() > 0)
    {
        <table class="table table-bordered table-striped" style="width:100%">
            <thead>
                <tr>
                    <th>Item Name</th>
                    <th>Borrower</th>
                    <th>Lender</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td width="30%">@item.ItemName</td>
                        <td width="30%">@item.Borrower</td>
                        <td width="30%">@item.Lender</td>
                    </tr>
                }
            </tbody>
        </table>
    }
</div>

InAndOut/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - InAndOut</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">InAndOut</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Item" asp-action="Index">My Borrowed Items</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Expense" asp-action="Index">My Expences</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - InAndOut - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>